#!/bin/bash

echo "🔍 Debugging Route Generation Issue"
echo "===================================="

echo ""
echo "1. ✅ Checking if app is running:"
if curl -s http://localhost:8081 > /dev/null; then
    echo "   ✅ App is running at http://localhost:8081"
else
    echo "   ❌ App not running. Please run 'npm run dev' first."
    exit 1
fi

echo ""
echo "2. 🔍 Key questions to investigate:"
echo "   - Do you have vehicles with packages?"
echo "   - Do the vehicles have coordinates (lat/lng)?"
echo "   - Do the packages have destination coordinates?"
echo "   - Is the MapBox token working?"

echo ""
echo "3. 🧪 Testing steps to perform:"
echo "=========================="
echo ""
echo "Step 1: Add a test vehicle"
echo "   - Go to 'Add Vehicle' tab"
echo "   - Vehicle ID: TEST-001"
echo "   - Driver: Test Driver"
echo "   - Location: Type 'San Francisco, CA' and select from dropdown"
echo "   - Click Submit"
echo ""
echo "Step 2: Add a test package"
echo "   - Go to 'Add Package' tab"
echo "   - Package ID: PKG-TEST"
echo "   - Vehicle: Select TEST-001"
echo "   - Destination: Type 'Oakland, CA' and select from dropdown"
echo "   - Weight: 10"
echo "   - Recipient: Test Customer"
echo "   - Click Submit"
echo ""
echo "Step 3: Generate route"
echo "   - Go to 'Fleet' tab"
echo "   - Click on vehicle TEST-001 on the map"
echo "   - In the sidebar, click '🗺️ Generate Route' button"
echo "   - Check browser console (F12) for detailed logs"
echo ""
echo "4. 🔍 What to look for in browser console:"
echo "========================================"
echo "✅ Expected logs when clicking Generate Route:"
echo "   🚀 Generating route for vehicle TEST-001"
echo "   📍 Creating route with X destinations"
echo "   🌐 MapBox API coordinates string: lng,lat;lng,lat"
echo "   📡 Making request to MapBox Directions API..."
echo "   ✅ MapBox API success: {...}"
echo "   🗺️ Route displayed on map for TEST-001"
echo ""
echo "❌ Error logs to watch for:"
echo "   ❌ Vehicle TEST-001 has no coordinates"
echo "   ❌ Vehicle TEST-001 has no packages"
echo "   ❌ MapBox token not available"
echo "   ❌ MapBox API error: {...}"
echo ""
echo "5. 🎯 Visual checks:"
echo "=================="
echo "✅ Debug panel (bottom right) should show:"
echo "   - Vehicles: 1+ (after adding vehicles)"
echo "   - With Packages: 1+ (after adding packages)"
echo "   - MapBox Token: ✅"
echo ""
echo "✅ On the map after generating route:"
echo "   - Blue curved line from vehicle to package destination"
echo "   - Line should follow roads, not be straight"
echo "   - Checkpoints/markers at destinations"
echo ""
echo "6. 🚨 Common issues and fixes:"
echo "=============================="
echo "Issue: 'No coordinates' error"
echo "   → Make sure you selected an address from the dropdown"
echo "   → Don't just type text - select the autocomplete suggestion"
echo ""
echo "Issue: 'No packages' error"  
echo "   → Make sure package was assigned to the correct vehicle"
echo "   → Check that package destination has coordinates"
echo ""
echo "Issue: MapBox API error"
echo "   → Check internet connection"
echo "   → Verify MapBox token is valid"
echo "   → Check browser network tab for failed requests"
echo ""
echo "7. 🎉 Success indicators:"
echo "========================"
echo "✅ Blue route line appears on map following roads"
echo "✅ Console shows all success messages"
echo "✅ Vehicle sidebar shows route distance/duration"
echo "✅ Debug panel shows 'With Routes: 1+'"

echo ""
echo "Open browser console (F12) and follow the steps above! 🚀"